# Generated by Django 3.1.7 on 2021-03-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao']},
        ),
    ]
