# Generated by Django 3.2.5 on 2021-08-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20210319_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='qtde',
        ),
        migrations.AddField(
            model_name='categoria',
            name='sigla',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidmedida',
            name='sigla',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sigla'),
        ),
    ]
