# Generated by Django 3.2.5 on 2021-08-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_desc_nf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='unidmedida',
            old_name='nome',
            new_name='descricao',
        ),
    ]
