# Generated by Django 3.2.5 on 2021-08-31 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelasbasicas', '0001_initial'),
        ('produtos', '0008_auto_20210829_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelasbasicas.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='und_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelasbasicas.unidmedida'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='UnidMedida',
        ),
    ]
