# Generated by Django 3.2.5 on 2021-10-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20210831_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='desc_nf',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
