# Generated by Django 3.1.7 on 2021-03-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=95, null=True)),
                ('rsocial', models.CharField(blank=True, max_length=95, null=True)),
                ('ie', models.CharField(blank=True, max_length=95, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=95, null=True)),
                ('cep', models.CharField(blank=True, max_length=95, null=True)),
                ('endereco', models.CharField(blank=True, max_length=95, null=True)),
                ('bairro', models.CharField(blank=True, max_length=95, null=True)),
                ('fone', models.CharField(blank=True, max_length=95, null=True)),
                ('cel', models.CharField(blank=True, max_length=95, null=True)),
                ('email', models.CharField(blank=True, max_length=95, null=True)),
                ('endnumero', models.CharField(blank=True, max_length=95, null=True)),
                ('cidade', models.CharField(blank=True, max_length=95, null=True)),
                ('estado', models.CharField(blank=True, max_length=95, null=True)),
            ],
        ),
    ]
