# Generated by Django 3.2.5 on 2021-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_auto_20210829_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
