# Generated by Django 3.1.7 on 2021-03-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20210310_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdavenda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
