# Generated by Django 3.1.7 on 2021-03-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20210310_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdavenda',
            old_name='total',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='valor',
            new_name='total',
        ),
    ]
