# Generated by Django 3.1.7 on 2021-03-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20210310_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['data', 'cliente']},
        ),
    ]
