# Generated by Django 3.1.7 on 2021-03-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0006_auto_20210313_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data', 'cliente__nome']},
        ),
        migrations.AlterUniqueTogether(
            name='itemdavenda',
            unique_together={('venda', 'produto')},
        ),
    ]
