# Generated by Django 3.1.7 on 2021-03-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('vendas', '0007_auto_20210313_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdavenda',
            old_name='desconto',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='itemdavenda',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='numero',
        ),
        migrations.AddField(
            model_name='venda',
            name='nparcelas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venda',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.tipopagamento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ParcelaVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('datapagto', models.DateField()),
                ('datavecto', models.DateField()),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda')),
            ],
        ),
    ]
