# Generated by Django 3.1.7 on 2021-03-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_auto_20210317_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdavenda',
            old_name='quantidade',
            new_name='qtde',
        ),
    ]
