# Generated by Django 3.1.7 on 2021-03-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_auto_20210319_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('PG', 'Pago'), ('VD', 'Vencido'), ('AV', 'A vender')], default='AV', max_length=2),
        ),
    ]
