# Generated by Django 3.1.7 on 2021-03-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_auto_20210319_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelavenda',
            name='datapagto',
            field=models.DateField(null=True),
        ),
    ]
