# Generated by Django 3.2.5 on 2021-07-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20210323_1217'),
        ('vendas', '0011_auto_20210323_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_criacao', 'cliente__nome']},
        ),
        migrations.RemoveField(
            model_name='venda',
            name='data',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='status',
        ),
        migrations.AddField(
            model_name='parcelavenda',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.tipopagamento'),
        ),
        migrations.AddField(
            model_name='parcelavenda',
            name='status',
            field=models.CharField(choices=[('PG', 'Paga'), ('VD', 'Vencida'), ('AV', 'A vencer'), ('NG', 'Negociada')], default='AV', max_length=2),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_criacao',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='num_venda',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Número da venda'),
        ),
        migrations.AlterField(
            model_name='parcelavenda',
            name='datapagto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcelavenda',
            name='datavecto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Negociacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_negoc', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor da negocioção')),
                ('qtde_parcelas', models.IntegerField(default=1, verbose_name='Quantidade de parcelas')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.parcelavenda')),
            ],
        ),
    ]
