# Generated by Django 3.2.5 on 2021-07-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_auto_20210718_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Negociacao',
            new_name='NegociacaoParcela',
        ),
    ]
