# Generated by Django 3.2.5 on 2021-07-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20210323_1217'),
        ('vendas', '0013_rename_negociacao_negociacaoparcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='negociacaoparcela',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.tipopagamento'),
        ),
    ]
