# Generated by Django 3.2.5 on 2021-07-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_negociacaoparcela_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='negociacaoparcela',
            name='datavecimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
