# Generated by Django 3.2.5 on 2021-08-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0016_auto_20210810_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelavenda',
            name='negociada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Parcela negociada'),
        ),
        migrations.AlterField(
            model_name='parcelavenda',
            name='status',
            field=models.CharField(choices=[('PG', 'Paga'), ('VD', 'Vencida'), ('AV', 'A vencer')], default='AV', max_length=2),
        ),
    ]
