# Generated by Django 3.2.5 on 2021-08-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0017_auto_20210814_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negociacaoparcela',
            name='datavecimento',
        ),
        migrations.RemoveField(
            model_name='negociacaoparcela',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='negociacaoparcela',
            name='qtde_parcelas',
        ),
    ]
