# Generated by Django 3.2.5 on 2021-08-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0018_auto_20210814_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aberta'), (2, 'Finalizada')], default=1),
        ),
    ]
