# Generated by Django 3.2.5 on 2021-08-31 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelasbasicas', '0001_initial'),
        ('vendas', '0019_venda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelavenda',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelasbasicas.tipopagamento'),
        ),
    ]
