# Generated by Django 3.2.5 on 2021-09-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0020_alter_parcelavenda_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
