# Generated by Django 3.2.5 on 2021-08-31 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelasbasicas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipopagamento',
            old_name='nome',
            new_name='descricao',
        ),
    ]
