# Generated by Django 3.1.7 on 2021-03-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['descricao']},
        ),
    ]
