# Generated by Django 3.1.7 on 2021-03-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('data', models.DateTimeField()),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'ordering': [['-data', 'cliente']],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notaservico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas_servicos.notaservico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
        ),
    ]
