# Generated by Django 3.1.7 on 2021-03-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
    ]
