# Generated by Django 3.1.7 on 2021-03-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('PG', 'Pago'), ('VD', 'Vencido'), ('AV', 'A vencer')], default='AV', max_length=2),
        ),
    ]
