# Generated by Django 3.1.7 on 2021-03-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20210318_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-data', 'fornecedor__nome']},
        ),
    ]
