# Generated by Django 3.1.7 on 2021-03-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20210319_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelacompra',
            name='datapagto',
            field=models.DateField(null=True),
        ),
    ]
