# Generated by Django 3.2.5 on 2021-08-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('compras', '0005_auto_20210323_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='status',
        ),
        migrations.AddField(
            model_name='compra',
            name='numcompra',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='parcelacompra',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.tipopagamento'),
        ),
        migrations.AddField(
            model_name='parcelacompra',
            name='status',
            field=models.CharField(blank=True, choices=[('PG', 'Pago'), ('VD', 'Vencido'), ('AV', 'A vencer')], default='AV', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nfiscal',
            field=models.IntegerField(verbose_name='Número NF-e'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nparcelas',
            field=models.IntegerField(default=1, verbose_name='Parcelas'),
        ),
    ]
