# Generated by Django 3.2.5 on 2021-08-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20210815_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='numcompra',
            new_name='num_compra',
        ),
    ]
