# Generated by Django 3.2.5 on 2021-08-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_numcompra_compra_num_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopagamento',
            name='sigla',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sigla'),
        ),
    ]
