# Generated by Django 3.2.5 on 2021-08-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_tipopagamento_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopagamento',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Sigla'),
        ),
    ]
