# Generated by Django 3.2.5 on 2021-08-31 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabelasbasicas', '0001_initial'),
        ('vendas', '0020_alter_parcelavenda_pagamento'),
        ('compras', '0009_alter_tipopagamento_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelacompra',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabelasbasicas.tipopagamento'),
        ),
        migrations.DeleteModel(
            name='TipoPagamento',
        ),
    ]
